import test from 'node:test';import assert from 'node:assert/strict';
import {inspectPayload, displayName, validateSelection, publicCatalog, HOSTED, LIMITS} from '../server/payloads.mjs';
function elf(){const b=Buffer.alloc(128);b.writeUInt32LE(0x464c457f);b[4]=2;b[5]=1;b[6]=1;b.writeUInt16LE(3,16);b.writeUInt16LE(62,18);b.writeBigUInt64LE(0n,24);b.writeBigUInt64LE(64n,32);b.writeUInt16LE(64,52);b.writeUInt16LE(56,54);b.writeUInt16LE(1,56);b.writeUInt32LE(1,64);b.writeUInt32LE(5,68);b.writeBigUInt64LE(128n,96);b.writeBigUInt64LE(128n,104);return b;}
test('valid upload gets a content hash, not a compatibility claim',()=>{const r=inspectPayload(elf());assert.equal(r.bytes,128);assert.match(r.sha256,/^[a-f0-9]{64}$/);assert.equal(r.compatible,undefined);});
test('untrusted directory names never become paths',()=>{assert.equal(displayName('../../folder/payload.elf'),'payload.elf');assert.equal(displayName('folder\\payload.bin'),'payload.bin');for(const x of ['.','..','evil\r\nSTOR.elf','a.zip','a'.repeat(181)+'.elf'])assert.throws(()=>displayName(x));});
test('rejects truncated and out-of-bounds program headers',()=>{const b=elf();b.writeBigUInt64LE(0xffffffffffffffffn,32);assert.throws(()=>inspectPayload(b));assert.throws(()=>inspectPayload(Buffer.alloc(63)));});
test('rejects truncated segments and invalid entry points',()=>{const b=elf();b.writeBigUInt64LE(129n,96);assert.throws(()=>inspectPayload(b));const c=elf();c.writeBigUInt64LE(129n,24);assert.throws(()=>inspectPayload(c));});
test('rejects unexpected architecture, SELF and excessive memory',()=>{for(const mutate of [b=>b.writeUInt16LE(183,18),b=>b.writeUInt16LE(0xfe10,16),b=>b.writeBigUInt64LE(600n*1024n**2n,104)]){const b=elf();mutate(b);assert.throws(()=>inspectPayload(b));}});
test('selection preserves requested order and enforces known dependencies',()=>{assert.deepEqual(validateSelection(['etahen','debug','shadowmount']).map(x=>x.id),['etahen','debug','shadowmount']);assert.throws(()=>validateSelection(['debug']));assert.throws(()=>validateSelection(['shadowmount','etahen']));assert.throws(()=>validateSelection(['etahen','etahen']));});
test('custom uploads cannot duplicate a hosted payload under a different name',()=>{assert.throws(()=>validateSelection(['etahen','upload-x'],[{...HOSTED[0],id:'upload-x'}]));});
test('selection rejects unknown files and total size overflow',()=>{assert.throws(()=>validateSelection(['../../x']));assert.throws(()=>validateSelection(['upload-a','upload-b','upload-c'],['a','b','c'].map((x)=>({id:'upload-'+x,sha256:x,bytes:LIMITS.fileBytes}))));});
test('public catalog does not expose local paths',()=>{assert.ok(publicCatalog().every(x=>!('input' in x)));});
