import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../startup.js',import.meta.url),'utf8');
function payload(id,acknowledgement='supervisor'){return{id,label:id,file:id+'.elf',bytes:64,acknowledgement,...(id==='etahen-ready'?{internal:true}:{})};}
function harness(manifest,send){const calls=[],notices=[];const io={log:()=>{},notify:s=>notices.push(s),returnHome:async()=>calls.push('home'),dispose:()=>{},verify:async()=>true,read:async()=>{const b=new Uint8Array(64);b.set([127,69,76,70,2,1]);b[18]=62;return b;},send:async item=>{calls.push(item.id);return send?send(item):item.acknowledgement==='supervisor'?{code:0}:{sent:true};}};const factory=vm.runInNewContext(source+'\ncreateSnipersStartup',{Uint8Array,Set});return{startup:factory(io,manifest),calls,notices};}
const state={handedOff:true,disarmed:true,crossed:false};
test('etaHEN-only selection still waits for actual readiness',async()=>{const h=harness([payload('etahen','etahen'),payload('etahen-ready')]);const files=await h.startup.prepare('13.60');await h.startup.run(files,state);assert.deepEqual(h.calls,['home','etahen','etahen-ready']);assert.equal(h.notices.length,1);await assert.rejects(h.startup.run(files,state),/already attempted/);});
test('failed etaHEN readiness prevents every optional and custom payload',async()=>{const h=harness([payload('etahen','etahen'),payload('etahen-ready'),payload('debug'),payload('upload-x','dispatch')],item=>item.id==='etahen-ready'?{code:-2}:{sent:true});const files=await h.startup.prepare('13.60');await assert.rejects(h.startup.run(files,state),/readiness/);assert.deepEqual(h.calls,['home','etahen','etahen-ready']);assert.equal(h.notices.length,0);});
test('custom dispatch completion is not represented as readiness',async()=>{const h=harness([payload('upload-x','dispatch')]);const files=await h.startup.prepare('13.60');await h.startup.run(files,state);assert.match(h.notices[0],/check their own status/);});
test('invalid readiness sequence and unconfirmed kernel handoff cannot send payloads',async()=>{const bad=harness([payload('etahen','etahen'),payload('debug')]);await assert.rejects(bad.startup.prepare('13.60'),/readiness/);const h=harness([payload('upload-x','dispatch')]);const files=await h.startup.prepare('13.60');await assert.rejects(h.startup.run(files,{...state,crossed:true}),/handoff/);assert.deepEqual(h.calls,[]);});
